#!/usr/bin/env bash
# =============================================================================
# REFRESH REFERENCES SNAPSHOT
# =============================================================================
# Clones or updates the TypeScript reference implementation as a read-only
# snapshot for parity testing and architectural guidance.
# =============================================================================

set -euo pipefail

# Configuration
REPO_URL="https://github.com/Luiz-Frias/semantic-code-for-agents.git"
BRANCH="dev" # Use dev branch for parity testing
REFERENCES_DIR="references/semantic-code-for-agents"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"

cd "$PROJECT_ROOT"

echo "╔══════════════════════════════════════════════════════════════════╗"
echo "║  Refreshing TypeScript Reference Snapshot                        ║"
echo "╚══════════════════════════════════════════════════════════════════╝"
echo ""

# Remove existing snapshot if present
if [[ -d "$REFERENCES_DIR" ]]; then
  echo "→ Removing existing snapshot..."
  rm -rf "$REFERENCES_DIR"
fi

# Clone and checkout dev branch
echo "→ Cloning from $REPO_URL..."
git clone "$REPO_URL" "$REFERENCES_DIR"

echo "→ Checking out $BRANCH branch..."
cd "$REFERENCES_DIR"
git checkout "$BRANCH"
git pull origin "$BRANCH"
cd "$PROJECT_ROOT"

# Remove .git to create detached snapshot (not a submodule)
echo "→ Detaching from git history..."
rm -rf "$REFERENCES_DIR/.git"

# Record snapshot metadata
SNAPSHOT_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
cat >"$REFERENCES_DIR/.snapshot-info" <<EOF
# Reference Snapshot Metadata
# This file is auto-generated by refresh-references.sh

snapshot_date: $SNAPSHOT_DATE
source_repo: $REPO_URL
source_branch: $BRANCH
EOF

echo ""
echo "✓ Reference snapshot updated successfully"
echo "  Location: $REFERENCES_DIR"
echo "  Date: $SNAPSHOT_DATE"
echo ""
echo "Note: This directory is git-ignored. Run this script again to update."
